---
- hosts: buildmaster
  remote_user: centos
  tasks:
  - name: Create Kudo yaml manifests directory
    file:
      path: /home/centos/kudo
      owner: centos
      group: centos
      mode: '0775'
      state: directory
  - name: Download Go (can't use yum because version too old)
    get_url:
      url: https://dl.google.com/go/go1.13.linux-amd64.tar.gz
      dest: /home/centos/kudo/go.tar.gz
      checksum: sha256:68a2297eb099d1a76097905a2ce334e3155004ec08cdea85f24527be3c48e856
  - name: Install GCC
    become: yes
    yum:
      name: gcc
      state: present
  - name: Install go
    become: yes
    unarchive:
      remote_src: yes
      src: /home/centos/kudo/go.tar.gz
      dest: /usr/local
  - name: Clean up the go archive
    file:
      path: /home/centos/kudo/go.tar.gz
      state: absent
  - name: Copy Go onto root's path
    become: yes
    copy:
      remote_src: yes
      src: /usr/local/go/bin/go
      dest: /sbin/go
      mode: '0755'
  - name: Get the kudo source
    git:
      repo: 'https://github.com/kudobuilder/kudo.git'
      dest: /home/centos/kudo
  - name: Create the output binary destination
    file:
      path: /home/centos/bin
      state: directory
  - name: Build the kubectl kudo plugin
    become: yes
    environment:
      GOBIN: /home/centos/bin
    make:
      chdir: /home/centos/kudo
      target: cli-install
  - name: Move the kubectl kudo plugin to path
    become: yes
    copy:
      remote_src: yes
      src: /home/centos/bin/kubectl-kudo
      dest: /usr/bin
      mode: '0755'
  - name: Download the binary
    fetch:
      src: /home/centos/bin/kubectl-kudo
      dest: ./scripts/
      flat: yes
  - name: Clean up bin
    file:
      path: /home/centos/bin
      state: absent
  - name: Clean up kudo
    file: 
      path: /home/centos/kudo
      state: absent
