---
- hosts: masters
  remote_user: centos
  tasks:        
  - name: Create helm yaml manifests directory
    file:
      path: /home/centos/helm
      owner: centos
      group: centos
      mode: '0775'
      state: directory
  - name: Download v3.0.0.b3 of Helm
    get_url:
      url: https://get.helm.sh/helm-v3.0.0-beta.3-linux-amd64.tar.gz
      dest: /home/centos/helm/helm.tar.gz
      checksum: sha256:23705380590bdb3e70e1bc8649fe1c90a75905bdc12ae6e6f6a9c16db9801594
  - name: Extract helm  
    unarchive:
      remote_src: yes
      src: /home/centos/helm/helm.tar.gz
      dest: /home/centos/helm
  - name: Move binary to path
    become: yes
    copy:
      remote_src: yes
      src: /home/centos/helm/linux-amd64/helm
      dest: /usr/bin/helm
      mode: '0755'
  - name: Add Default "stable" helm repo
    command: helm repo add stable https://kubernetes-charts.storage.googleapis.com
  - name: Update Stable repo
    command: helm repo update
