---
- hosts: masters
  remote_user: centos
  tasks:        
  - name: Create helm yaml manifests directory
    file:
      path: /home/centos/helm
      owner: centos
      group: centos
      mode: '0775'
      state: directory
  - name: Download v2.14.3 of Helm
    get_url:
      url: https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz
      dest: /home/centos/helm/helm.tar.gz
      checksum: sha256:38614a665859c0f01c9c1d84fa9a5027364f936814d1e47839b05327e400bf55
  - name: Extract helm  
    unarchive:
      remote_src: yes
      src: /home/centos/helm/helm.tar.gz
      dest: /home/centos/helm
  - name: Move binary to path
    become: yes
    copy:
      remote_src: yes
      src: /home/centos/helm/linux-amd64/helm
      dest: /usr/bin/helm
      mode: '0755'
  - name: Create service account
    command: kubectl create serviceaccount --namespace kube-system tiller
  - name: Bind to the appropriate role
    command: kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
  - name: Initialize Helm & Install Tiller
    command: helm init --history-max 200 --service-account tiller
  #- name: Patch the tiller deployment to use the service account
  #  command: kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
