---
- hosts: masters
  remote_user: centos
  tasks:        
  - name: Create istio yaml manifests directory
    file:
      path: /home/centos/istio
      owner: centos
      group: centos
      mode: '0775'
      state: directory
  - name: Download v1.4.3 of Istio
    get_url:
      url: https://github.com/istio/istio/releases/download/1.4.3/istio-1.4.3-linux.tar.gz
      dest: /home/centos/istio/istio.tar.gz
      checksum: sha256:781e2c4391ba344d86fb6a4c321b76af31543e7479ea689dd7c7395fb1a41ff0
  - name: Extract istio
    unarchive:
      remote_src: yes
      src: /home/centos/istio/istio.tar.gz
      dest: /home/centos/istio
  - name: Move istioctl to path
    become: yes
    copy:
      remote_src: yes
      src: /home/centos/istio/istio-1.4.3/bin/istioctl
      dest: /usr/bin/istioctl
      mode: '0755'
  - name: Install Istio in "Demo" mode
    command: kubectl apply -f /home/centos/istio/istio-1.4.3/install/kubernetes/istio-demo.yaml
