---
- hosts: masters
  remote_user: ubuntu
  tasks:        
  - name: Create Ingress yaml manifests directory
    file:
      path: /home/ubuntu/ingress
      owner: ubuntu
      group: ubuntu
      mode: '0775'
      state: directory
  - name: Upload setup manifest
    copy:
      src: ./scripts/ingress/01-ingress-ns-config.yaml
      dest: /home/ubuntu/ingress/ingress-ns-config.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0664'
  - name: Upload default backend manifest
    copy:
      src: ./scripts/ingress/02-ingress-default-backend.yaml
      dest: /home/ubuntu/ingress/ingress-default-backend.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'
  - name: Upload load balancer manifest
    copy:
      src: ./scripts/ingress/03-ingress-lb.yaml
      dest: /home/ubuntu/ingress/ingress-lb.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'
  - name: Upload the whoami test manifest
    copy:
      src: ./scripts/ingress/04-whoami-test.yaml
      dest: /home/ubuntu/ingress/whoami-test.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'
  - name: Create the Namespace & ConfigMaps
    command: kubectl apply -f /home/ubuntu/ingress/ingress-ns-config.yaml
  - name: create the ingress controller objects
    command: kubectl apply -f /home/ubuntu/ingress/ingress-default-backend.yaml
  - name: create the ingress load balancer objects
    command: kubectl apply -f /home/ubuntu/ingress/ingress-lb.yaml
  - name: Create the whoami test
    command: kubectl apply -f /home/ubuntu/ingress/whoami-test.yaml
