---
- hosts: masters
  remote_user: centos
  tasks:        
  - name: Create istio yaml manifests directory
    file:
      path: /home/centos/istio
      owner: centos
      group: centos
      mode: '0775'
      state: directory
  - name: Download v1.3.1 of Istio
    get_url:
      url: https://github.com/istio/istio/releases/download/1.3.1/istio-1.3.1-linux.tar.gz
      dest: /home/centos/istio/istio.tar.gz
      checksum: sha256:72cf2a931dd20509ea21bdceb16d8330d53d7e236e1a26fffc24a54404998389 
  - name: Extract istio
    unarchive:
      remote_src: yes
      src: /home/centos/istio/istio.tar.gz
      dest: /home/centos/istio
  - name: Move istioctl to path
    become: yes
    copy:
      remote_src: yes
      src: /home/centos/istio/istio-1.3.1/bin/istioctl
      dest: /usr/bin/istioctl
      mode: '0755'
  - name: Copy CRD creation script to host
    copy:
      src: ./scripts/create-istio-crds.sh
      dest: /home/centos/istio/create-crds.sh
      mode: '0755'
  - name: Create CRDs
    command: /home/centos/istio/create-crds.sh
  - name: Install Istio in "Demo" mode
    command: kubectl apply -f /home/centos/istio/istio-1.3.1/install/kubernetes/istio-demo.yaml
