---
- hosts: all
  remote_user: ubuntu
  gather_facts: no
  tasks:
  - name: Wait for cluster
    wait_for_connection:
  - name: Now gather facts...
    setup:
  - name: Set color prompt
    lineinfile:
      dest: /home/ubuntu/.bashrc
      regexp: '^#force_color_prompt.*$'
      line: 'force_color_prompt=yes'
