---
#  - name: Install Kubernetes components via apt
#    become: yes
#    apt:
#      pkg:
#      - kubelet=1.18.2-00
#      - kubeadm=1.18.2-00 
#      - kubectl=1.18.2-00
#      state: present
- hosts: masters
  remote_user: ubuntu
  tasks:        
  - name: Drain Master Node Host:[{{ansible_hostname}}]
    command: kubectl drain {{ansible_hostname}} --ignore-daemonsets
  - name: Update Kubeadm to v1.18.3
    become: yes
    apt:
      pkg: kubeadm=1.18.3-00
      state: present
  - name: Run kubeadm upgrade plan on master
    become: yes
    command: kubeadm upgrade plan
  - name: Run the upgrade on the master
    become: yes
    command: kubeadm upgrade apply v1.18.3 -y
  - name: Upgrade the kubelet and kubectl on master
    become: yes
    apt:
      pkg:
      - kubelet=1.18.3-00
      - kubectl=1.18.3-00
  - name: Uncordon the master
    command: kubectl uncordon {{ansible_hostname}}
- hosts: minions
  remote_user: ubuntu
  serial: 1
  tasks:
  - name: Drain Worker [{{ansible_hostname}}] on [{{cluster_master}}]
    command: "kubectl drain {{ansible_hostname}} --ignore-daemonsets --delete-local-data"
    delegate_to: "{{cluster_master}}"
  - name: Upgrade Kubeadm on worker
    become: yes
    apt:
      pkg: kubeadm=1.18.3-00
      state: present
  - name: Upgrade node with Kubeadm
    become: yes
    command: kubeadm upgrade node
  - name: Upgrade Kubelet on Worker
    become: yes
    apt:
      pkg: kubelet=1.18.3-00
      state: present
  - name: Uncordon Worker [{{ansible_hostname}}] on {{cluster_master}}
    command: "kubectl uncordon {{ansible_hostname}}"
    delegate_to: "{{cluster_master}}"
