---
- hosts: masters
  remote_user: centos
  tasks:        
  - name: Create Ingress yaml manifests directory
    file:
      path: /home/centos/ingress
      owner: centos
      group: centos
      mode: '0775'
      state: directory
  - name: Upload sock shop manifest
    copy:
      src: ./scripts/ingress/05-sockshop-test.yaml
      dest: /home/centos/ingress/05-sockshop-test.yaml
      owner: centos
      group: centos
      mode: '0644'
